### PR TITLE
Add new Jsp Property Group setting error-on-el-not-found

### PR DESCRIPTION
**Pull request by markt-asf**
This is to support implementation of [EL #40](https://github.com/eclipse-ee4j/jsp-api/issues/40)

Additional PRs will be submitted to servlet-api and jsp-api

### CODE REVIEW

**Comment by markt-asf** [comment]
Ping. Could I get a review (and approval?) please. This is blocking progress on the JSP API.

**Review by ivargrimstad — APPROVED** [review]

**Comment by ivargrimstad** [comment]
Hi @markt-asf,

Are you able to merge it yourself, or do you want me to do it?

Ivar

**Comment by markt-asf** [comment]
Can you merge it please. I don't have commit rights here. Tx.

**Comment by markt-asf** [comment]
Tx.

**Pull request merged**
